
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Faiqoh
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        tnis = new javax.swing.JTextField();
        tkls = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        talamat = new javax.swing.JTextArea();
        rbpr = new javax.swing.JRadioButton();
        rblk = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        btnsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jButton4.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" FORM BIODATA SISWA SMK TELKOM MALANG");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 490, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The Real Informatic School");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 60, 160, 15);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 100);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Jenis Kelamin", "Kelas", "Email", "Alamat"
            }
        ));
        tbldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbldata);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 560, 440);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(300, 170, 600, 480);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("ALAMAT");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 310, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("NIS");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 10, 40, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("NAMA");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 70, 50, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("JENIS KELAMIN");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 130, 110, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("KELAS");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 190, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("EMAIL");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 250, 110, 30);
        jPanel3.add(temail);
        temail.setBounds(20, 280, 250, 30);
        jPanel3.add(tnama);
        tnama.setBounds(20, 100, 250, 30);
        jPanel3.add(tnis);
        tnis.setBounds(20, 40, 250, 30);
        jPanel3.add(tkls);
        tkls.setBounds(20, 220, 250, 30);

        talamat.setColumns(20);
        talamat.setRows(5);
        jScrollPane1.setViewportView(talamat);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 340, 250, 130);

        rbpr.setText("PEREMPUAN");
        rbpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbprActionPerformed(evt);
            }
        });
        jPanel3.add(rbpr);
        rbpr.setBounds(150, 160, 120, 23);

        rblk.setText("LAKI_LAKI");
        jPanel3.add(rblk);
        rblk.setBounds(20, 160, 110, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 160, 290, 490);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(null);

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnsave);
        btnsave.setBounds(10, 10, 110, 30);

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btndelete);
        btndelete.setBounds(130, 10, 100, 30);

        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel4.add(btnedit);
        btnedit.setBounds(480, 10, 100, 30);

        btnrefresh.setText("REFRESH");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        jPanel4.add(btnrefresh);
        btnrefresh.setBounds(360, 10, 110, 30);

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel4.add(btnclear);
        btnclear.setBounds(240, 10, 110, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(300, 110, 600, 50);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ISIAN DATA SISWA");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(50, 0, 160, 40);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 110, 290, 40);

        setBounds(0, 0, 913, 689);
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data?","", JOptionPane.YES_NO_OPTION);
        int baris = tbldata.getSelectedRow();
        if (confirm==0) {
            
        
        if (baris != -1) {
            String NIS = tbldata.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "DATA gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        } }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        if ("".equals(tnis.getText()) || "".equals(talamat.getText()) || "".equals(tkls.getText()) || 
                "".equals(tnama.getText()) || "".equals(temail.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data Anda", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String JK = "";
            if (rblk.isSelected()) {
                JK = "L";
            } else {
                JK = "P";
            }
            String SQL = "INSERT INTO t_siswa (NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat)"
                    + "VALUES('"+tnis.getText()+"','"+tnama.getText()+"','"+JK+"',"
                    +"'"+tkls.getText()+"','"+temail.getText()+"','"+talamat.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil ditambahakan", "Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahakan","Sukses",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        tnis.setText("");
        tnama.setText("");
        tkls.setText("");
        temail.setText("");
        talamat.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        int baris = tbldata.getSelectedRow();
            String nis = tbldata.getValueAt(baris, 0).toString();
        if ("".equals(tnis.getText()) || "".equals(talamat.getText()) || "".equals(tkls.getText())||"".equals(tnama.getText())||"".equals(temail.getText())){
            
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
        }else{
            String JK ="";
            if (rblk.isSelected()) {
                JK = "L";
            }else{
                JK = "P";
            }
            String SQL ="UPDATE `t_siswa` SET `NIS`='"+tnis.getText()+"',`NamaSiswa`='"+tnama.getText()+"',`JenisKelamin`='"+JK+"',`Kelas`='"+tkls.getText()+"',`Email`='"+temail.getText()+"',`Alamat`='"+talamat.getText()+"' WHERE NIS='"+nis+"'";

            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this,"Data berhasil diUpdate","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this,"Data gagal diUpdate","Sukses",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void tbldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataMouseClicked
        // TODO add your handling code here:
        int baris = tbldata.getSelectedRow();
        if (baris != -1) {
            tnis.setText(tbldata.getValueAt(baris, 0).toString());
            tnama.setText(tbldata.getValueAt(baris, 1).toString());
            if ("Laki-laki".equals(tbldata.getValueAt(baris, 2).toString())) 
                {
                rblk.setSelected(true);
            } else {
                rbpr.setSelected(true);
            }
            tkls.setText(tbldata.getValueAt(baris, 3).toString());
            temail.setText(tbldata.getValueAt(baris, 4).toString());
            talamat.setText(tbldata.getValueAt(baris, 5).toString());
        }
    }//GEN-LAST:event_tbldataMouseClicked

    private void rbprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbprActionPerformed
    
    private void selectData() {
        String kolom[] = {"NIS","NamaSiswa","JenisKelamin","Kelas","Email","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String NIS = rs.getString(1);
                String NamaSiswa = rs.getString(2);
                String JenisKelamin = "";
                if ("L".equals(rs.getString(3))) {
                    JenisKelamin = "Laki-Laki";
                } else {
                    JenisKelamin = "Perempuan";
                }
                String Kelas = rs.getString(4);
                String Email = rs.getString(5);
                String Alamat = rs.getString(6);
                String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat};
                dtm.addRow(data);
        }
    } catch (SQLException ex){
        Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
    }
        tbldata.setModel(dtm);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rblk;
    private javax.swing.JRadioButton rbpr;
    private javax.swing.JTextArea talamat;
    private javax.swing.JTable tbldata;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tkls;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnis;
    // End of variables declaration//GEN-END:variables

    
}
