
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Faiqoh
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setJam();
        setTanggal();
    }
        
        String nol_jam = "";
        String nol_menit = "";
        String nol_detik = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        ljam = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        tnis = new javax.swing.JTextField();
        tkls = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        talamat = new javax.swing.JTextArea();
        rbpr = new javax.swing.JRadioButton();
        rblk = new javax.swing.JRadioButton();
        tmp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tgl = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        btnsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jButton4.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" FORM BIODATA SISWA SMK TELKOM MALANG");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 490, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The Real Informatic School");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 60, 160, 15);

        tanggal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        tanggal.setText("Tanggal");
        jPanel1.add(tanggal);
        tanggal.setBounds(720, 20, 90, 30);

        ljam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ljam.setForeground(new java.awt.Color(255, 255, 255));
        ljam.setText("Jam");
        jPanel1.add(ljam);
        ljam.setBounds(720, 50, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 100);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Kelas", "Email", "Alamat"
            }
        ));
        tbldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbldata);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(0, 20, 600, 540);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(300, 170, 600, 560);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("ALAMAT");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 430, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("NIS");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 10, 40, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("NAMA");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 70, 50, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("JENIS KELAMIN");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 250, 110, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("KELAS");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 310, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("EMAIL");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 370, 110, 30);
        jPanel3.add(temail);
        temail.setBounds(20, 400, 250, 30);
        jPanel3.add(tnama);
        tnama.setBounds(20, 100, 250, 30);
        jPanel3.add(tnis);
        tnis.setBounds(20, 40, 250, 30);
        jPanel3.add(tkls);
        tkls.setBounds(20, 340, 250, 30);

        talamat.setColumns(20);
        talamat.setRows(5);
        jScrollPane1.setViewportView(talamat);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 460, 250, 100);

        buttonGroup1.add(rbpr);
        rbpr.setText("PEREMPUAN");
        rbpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbprActionPerformed(evt);
            }
        });
        jPanel3.add(rbpr);
        rbpr.setBounds(150, 280, 120, 23);

        buttonGroup1.add(rblk);
        rblk.setText("LAKI_LAKI");
        jPanel3.add(rblk);
        rblk.setBounds(20, 280, 110, 23);
        jPanel3.add(tmp);
        tmp.setBounds(20, 160, 250, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Tanggal Lahir");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 190, 120, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Tempat Lahir");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 130, 120, 30);
        jPanel3.add(tgl);
        tgl.setBounds(20, 220, 250, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 160, 290, 570);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(null);

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnsave);
        btnsave.setBounds(10, 10, 80, 30);

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btndelete);
        btndelete.setBounds(100, 10, 90, 30);

        btnprint.setText("PRINT");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel4.add(btnprint);
        btnprint.setBounds(490, 10, 70, 30);

        btnrefresh.setText("REFRESH");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        jPanel4.add(btnrefresh);
        btnrefresh.setBounds(300, 10, 100, 30);

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel4.add(btnclear);
        btnclear.setBounds(200, 10, 90, 30);

        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel4.add(btnedit);
        btnedit.setBounds(410, 10, 70, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(300, 110, 600, 50);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ISIAN DATA SISWA");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(50, 0, 160, 40);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 110, 290, 40);

        setBounds(0, 0, 913, 777);
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data?","", JOptionPane.YES_NO_OPTION);
        int baris = tbldata.getSelectedRow();
        if (confirm==0) {
            
        
        if (baris != -1) {
            String NIS = tbldata.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "DATA gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        } }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(tgl.getDate());
        if("".equals(tnis.getText()) || "".equals(tnama.getText()) ||
           "".equals(tmp.getText()) || "".equals(tanggal) ||
            "".equals(tkls.getText()) || "".equals(temail.getText()) ||
            "".equals(talamat.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            String JK = "";
            if(rblk.isSelected()){
                JK = "L";
            }else{
                JK = "P";
            }
            String SQL = "INSERT INTO t_siswa(NIS,NamaSiswa,TempatLahir,TanggalLahir,JenisKelamin,Kelas,Email,Alamat)"
            + "VALUES ('"+tnis.getText()
                    +"','"+tnama.getText()
                    +"','"+tmp.getText()
                    +"','"+tanggal
                    +"','"+JK
                    +"','"+tkls.getText()
                    +"','"+temail.getText()
                    +"','"+talamat.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        tnis.setText("");
        tnama.setText("");
        tmp.setText("");
        tkls.setText("");
        temail.setText("");
        talamat.setText("");
        tgl.setCalendar(null);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnclearActionPerformed
 
    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
       MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
       MessageFormat footer = new MessageFormat("Page {0,number,integer}    ");
       try{
           tbldata.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
       } catch (java.awt.print.PrinterException e){
           System.err.format("Cannot print %s%n", e.getMessage());
       }
    }//GEN-LAST:event_btnprintActionPerformed

    private void tbldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataMouseClicked
        // TODO add your handling code here:
        int baris = tbldata.getSelectedRow();
        if (baris != -1) {
            tnis.setText(tbldata.getValueAt(baris, 0).toString());
            tnama.setText(tbldata.getValueAt(baris, 1).toString());
            tmp.setText(tbldata.getValueAt(baris, 2).toString());
            SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat=null;
            try {
                dateFormat=date.parse(tbldata.getValueAt(baris, 3).toString());
            } catch (ParseException ex) {
                
            }
            tgl.setDate(dateFormat);
            if ("Laki-laki".equals(tbldata.getValueAt(baris, 4).toString())) 
                {
                rblk.setSelected(true);
            } else {
                rbpr.setSelected(true);
            }
            tkls.setText(tbldata.getValueAt(baris, 5).toString());
            temail.setText(tbldata.getValueAt(baris, 6).toString());
            talamat.setText(tbldata.getValueAt(baris, 7).toString());
        }
    }//GEN-LAST:event_tbldataMouseClicked

    private void rbprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbprActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        if("".equals(tnis.getText()) || "".equals(tnama.getText()) ||
            "".equals(tkls.getText()) || "".equals(temail.getText()) ||
            "".equals(talamat.getText()) || "".equals(tmp.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            int baris = tbldata.getSelectedRow();
            String nis = tbldata.getValueAt(baris, 0).toString();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = dateFormat.format(tgl.getDate());
            String JK = "";
            if(rblk.isSelected()){
                JK = "L";
            }else{
                JK = "P";
            }
            String sql = "UPDATE `t_siswa` SET `NIS`='"+tnis.getText()
                    +"',`NamaSiswa`='"+tnama.getText()
                    +"',`TempatLahir`='"+tmp.getText()
                    +"',`TanggalLahir`='"+tanggal
                    +"',`JenisKelamin`='"+JK
                    +"',`Kelas`='"+tkls.getText()
                    +"',`Email`='"+temail.getText()
                    +"',`Alamat`='"+talamat.getText()
                    +"' WHERE NIS="+nis;
            int status = KoneksiDB.execute(sql);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data Gagal Diupdate", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btneditActionPerformed
    
    private void selectData() {
        String kolom[] = {"NIS","NamaSiswa","TempatLahir","TanggalLahir","JenisKelamin","Kelas","Email","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String sql = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(sql);
        try{
            while(rs.next()){
                String NIS = rs.getString(1);
                String NamaSiswa = rs.getString(2);
                String TempatLahir = rs.getString(3);
                String TanggalLahir = rs.getString(4);
                String JenisKelamin = "";
                if("L".equals(rs.getString(5))){
                    JenisKelamin = "Laki-Laki";
                }else{
                    JenisKelamin = "Perempuan";
                }
                String Kelas = rs.getString(6);
                String Email = rs.getString(7);
                String Alamat = rs.getString(8);
                String data[] = {NIS,NamaSiswa,TempatLahir,TanggalLahir,JenisKelamin,Kelas,Email,Alamat};
                dtm.addRow(data);
            }
        }catch(SQLException ex){
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbldata.setModel(dtm);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }
    
    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        tanggal.setText(kal.format(skrg));
    }
    
    public void setJam(){
        ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam <= 9 ) {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9 ) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                ljam.setText("Jam "+ jam + ":" + menit + ":" + detik);
            }
        };
        new Timer(100, taskPerformer).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel ljam;
    private javax.swing.JRadioButton rblk;
    private javax.swing.JRadioButton rbpr;
    private javax.swing.JTextArea talamat;
    private javax.swing.JLabel tanggal;
    private javax.swing.JTable tbldata;
    private javax.swing.JTextField temail;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JTextField tkls;
    private javax.swing.JTextField tmp;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnis;
    // End of variables declaration//GEN-END:variables

    
}
